name: keyboard_hider
description: A tiny Flutter package to help you hide the keyboard.
version: 0.1.0
homepage: https://www.github.com/dartsidedev/keyboard_hider
repository: https://www.github.com/dartsidedev/keyboard_hider
issue_tracker: https://www.github.com/dartsidedev/keyboard_hider/issues
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mocktail: ^0.2.0
flutter:
